global:
  scrape_interval:     10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'vanus'
    static_configs:
      - targets:
          - controller:2112
          - gateway:2113
          - store:2114
          - timer:2115
          - trigger:2116
#    relabel_configs:
#      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
#        action: keep
#        regex: true
#      - source_labels: [__meta_kubernetes_pod_container_port_name]
#        action: keep
#        regex: metrics
#      - source_labels: [__meta_kubernetes_namespace]
#        action: keep
#        regex: vanus
#      - source_labels: [__meta_kubernetes_pod_name]
#        action: replace
#        target_label: pod_name
#      - source_labels: [__meta_kubernetes_pod_container_name]
#        action: replace
#        target_label: container_name
#      - source_labels: [__meta_kubernetes_pod_container_port_number]
#        action: replace
#        target_label: container_port_number